// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylffnkcwsvhkzqmujsms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsZmZua2N3c3Zoa3pxbXVqc21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTQ1MDksImV4cCI6MjA2MzYzMDUwOX0.hECHAq3M1pfG6NQbOly8zBrEvXA_IkZ2-LgsGtpySeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);